# Generated by Django 5.2.1 on 2025-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="certificates/")),
                ("hash", models.CharField(blank=True, editable=False, max_length=64)),
            ],
        ),
    ]
